@startuml
HTTPClient -> FlaskWebApp: GET /mine
FlaskWebApp -> Blockchain: (get) last_proof
Blockchain -> Block: (get) last_block.proof
Block -> Blockchain: proof
Blockchain -> FlaskWebApp: last_proof
FlaskWebApp -> Blockchain: proof_of_work(last_proof)
Blockchain -> FlaskWebApp: new_proof
FlaskWebApp -> Blockchain: new_transaction
FlaskWebApp -> Blockchain: new_block(new_proof)
Blockchain -> FlaskWebApp: block
FlaskWebApp -> JSON: dumps(response)
JSON -> HTTPClient: serialized response
@enduml
