@startuml
HTTPClient -> FlaskWebApp: GET /mine
FlaskWebApp -> Blockchain: (get attribute) last_block
Blockchain -> FlaskWebApp: last_block
FlaskWebApp -> Block: (get attribute) last_proof
Block -> FlaskWebApp: last_proof
FlaskWebApp -> Blockchain: proof_of_work(last_proof)
Blockchain -> FlaskWebApp: proof
FlaskWebApp -> Blockchain: new_transaction
FlaskWebApp -> Block: last_block.hash()
Block -> FlaskWebApp: previous_hash
FlaskWebApp -> Blockchain: new_block(proof, previous_hash)
Blockchain -> FlaskWebApp: block
FlaskWebApp -> JSON: dumps(response)
JSON -> HTTPClient: serialized response
@enduml
